In [16]:
import numpy as np
import pandas as pd
import time
import torch

In [17]:
csv_path = 'ashdod_kala.csv'
flight_times = torch.load('../raw/drone/pom_timestamps.pt', map_location='cpu', weights_only=False)
flight_time_list = flight_times.to_list()

In [18]:
modiin_csv = pd.read_csv('modiin.csv')
modiin_csv.head()

,0,EP_station_NO,EP_station_NO2,EP_station_NOX,EP_station_O3,EP_station_PM10,EP_station_PM2.5,EP_station_RH,EP_station_SO2,EP_station_Temp,EP_station_WD,EP_station_WS,EP_station_Rain,EP_station_CO,EP_station_Benzene,factor0
0,2023-05-01 00:05:00,0.4,4.0,4.5,100.5,20.3,NaN,NaN,4.6,NaN,136.0,1.4,NaN,NaN,NaN,NaN
1,2023-05-01 00:10:00,0.4,3.9,4.5,99.6,20.5,NaN,NaN,4.9,NaN,135.0,1.2,NaN,NaN,NaN,NaN
2,2023-05-01 00:15:00,0.5,4.6,5.3,98.3,20.9,NaN,NaN,5.0,NaN,134.0,1.6,NaN,NaN,NaN,NaN
3,2023-05-01 00:20:00,0.4,3.6,4.2,98.9,21.1,NaN,NaN,4.3,NaN,136.0,1.6,NaN,NaN,NaN,NaN
4,2023-05-01 00:25:00,0.4,3.4,4.0,100.7,21.1,NaN,NaN,4.4,NaN,140.0,1.4,NaN,NaN,NaN,NaN

In [19]:
shamat_csv = pd.read_csv('shamat.csv')
shamat_csv.head()

,Timestamp,shamat_P,shamat_RH,shamat_T,shamat_T_ground,shamat_T_max,shamat_T_min,shamat_precipitation,shamat_wind_direction,shamat_wind_direction_std_dev,shamat_wind_gust_direction,shamat_wind_gust_speed,shamat_wind_speed,shamat_wind_speed_10min_max,shamat_wind_speed_1min_max,shamat_U,shamat_V,shamat_U_corrected,shamat_V_corrected,rad
0,2023-05-01 00:00:00,1011.8,73.0,15.6,15.0,15.6,15.4,0.0,130.0,34.3,85.0,1.6,0.6,0.7,1.3,0.459627,-0.385673,-0.459627,0.385673,0.0
1,2023-05-01 00:10:00,1011.8,73.0,15.3,15.0,15.4,15.2,0.0,96.0,7.5,91.0,1.8,1.2,1.2,1.5,1.193426,-0.125434,-1.193426,0.125434,0.0
2,2023-05-01 00:20:00,1011.8,72.0,15.3,15.2,15.3,15.2,0.0,102.0,7.8,104.0,2.4,1.8,1.8,2.1,1.760666,-0.374241,-1.760666,0.374241,0.0
3,2023-05-01 00:30:00,1011.7,73.0,15.2,15.0,15.3,15.1,0.0,99.0,7.6,100.0,2.1,1.4,1.8,1.7,1.382764,-0.219008,-1.382764,0.219008,0.0
4,2023-05-01 00:40:00,1011.8,73.0,15.0,15.1,15.1,15.0,0.0,107.0,8.2,110.0,2.4,1.7,1.7,2.0,1.625718,-0.497032,-1.625718,0.497032,0.0

In [26]:
shamat_t = torch.load('../station_tensors/shamat.pt')
tel_aviv_levinsky = torch.load('../station_tensors/tel_aviv_levinsky.pt')